### ISSUE TITLE
error (NoMethodError)

### ISSUE THREAD

**Issue by jostrasser** [benningm/docker-telegraf-netatmo#2]
Hi, 

I think the script is broken since a few days:

./netatmo:81:in `filter_data': private method `select' called for nil:NilClass (NoMethodError)                                                                                                                                       
        from ./netatmo:75:in `process_data'                                                                                                                                                                                          
        from ./netatmo:102:in `measurements'                                                                                                                                                                                         
        from ./netatmo:120:in `<main>'                                   

Stopped working without any changes on the linux-side.

Any ideas?                     

Thanks JO

**Comment by jostrasser** [comment]
Found an issue with ruby. Thanks!

**Comment by AlfaJackal** [comment]
Hi @jostrasser 

I am experiencing the same error. Could you describe, how you exactly solved this problem?

Best,
AlfaJackal
