### ISSUE TITLE
Rain values are not accurate enough

### ISSUE THREAD

**Issue by jostrasser** [benningm/docker-telegraf-netatmo#6]
Hi @benningm 

If I compare the values between the my.netatmo.com portal and my self hosted Grafana which is getting the data via the netatmo data porter script from my InfluxDB I can see that the data on Grafana does not match them on the official Netatmo App / Web Portal.

Example:
Daily Rain (sum today)
On Netatmo: 10.4 mm
On Grafana: 7.5 mm

![rain_official](https://user-images.githubusercontent.com/14274103/94230271-e9c0d380-ff01-11ea-9807-e1752b310858.png)

![rain_grafana](https://user-images.githubusercontent.com/14274103/94230275-ed545a80-ff01-11ea-8d42-8ef3b59f461c.png)

Also the hourly data is not identical, that's the reason why the daily sum cannot be correct.

![hourly_official](https://user-images.githubusercontent.com/14274103/94230283-f2190e80-ff01-11ea-945d-b153c10f99ac.png)

![hourly_grafana](https://user-images.githubusercontent.com/14274103/94230292-f6ddc280-ff01-11ea-8f05-3b2ce238b4c0.png)

Any ideas?

Thanks JO!

**Comment by jostrasser** [comment]
What I have found:
https://any-api.com/netatmo_net/netatmo_net/docs/public/getmeasure

There is also an array function with "sum_rain"... but I don't know if it helps.
If it helps, then only for the daily value... the hourly cannot be fixed with it because the data will be pulled every 10mins.

**Comment by benningm** [comment]
The script does only retrieve the values from the API.
So this should not be a problem of the script.

I guess you have a rate and what you want is a counter value.
